wt4DanAllNLoweras31and4Precomputed = (
 + 1/2 IIi[{4}, {cri[{a, b, c, e}]}]
 + 5/2 IIi[{4}, {cri[{a, b, d, Inf}]}]
 - 2 IIi[{4}, {cri[{a, b, e, Inf}]}]
 + IIi[{4}, {cri[{a, b, Inf, c}]}]
 + 2 IIi[{4}, {cri[{a, c, b, d}]}]
 - IIi[{4}, {cri[{a, c, b, e}]}]
 + IIi[{4}, {cri[{a, c, d, Inf}]}]
 + IIi[{4}, {cri[{a, c, e, Inf}]}]
 - IIi[{4}, {cri[{a, c, Inf, b}]}]
 - IIi[{4}, {cri[{a, d, c, e}]}]
 + IIi[{4}, {cri[{a, d, e, Inf}]}]
 + 1/2 IIi[{4}, {cri[{a, d, Inf, b}]}]
 + 4 IIi[{4}, {cri[{a, d, Inf, c}]}]
 + IIi[{4}, {cri[{a, e, c, d}]}]
 + 1/2 IIi[{4}, {cri[{a, e, d, Inf}]}]
 - 3/2 IIi[{4}, {cri[{a, e, Inf, b}]}]
 + IIi[{4}, {cri[{a, e, Inf, c}]}]
 + IIi[{4}, {cri[{a, Inf, b, d}]}]
 - 2 IIi[{4}, {cri[{a, Inf, b, e}]}]
 + 2 IIi[{4}, {cri[{a, Inf, c, d}]}]
 + 3/2 IIi[{4}, {cri[{a, Inf, c, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, d, a, Inf, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, d, a, Inf, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, e, a, d, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, e, a, Inf, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, Inf, c, a, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, Inf, c, a, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, Inf, d, a, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, Inf, e, a, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, d, a, b, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, d, a, Inf, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, e, a, b, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, e, a, d, Inf}]}]
 - IIi[{3, 1}, {cri[{c, Inf, b, a, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, Inf, d, a, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, Inf, d, a, e}]}]
 - IIi[{3, 1}, {cri[{c, Inf, e, a, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, b, c, a, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, b, e, a, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, b, Inf, a, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, c, b, a, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, c, e, a, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, c, Inf, a, e}]}]
 + IIi[{3, 1}, {cri[{d, Inf, a, b, c}]}]
 - IIi[{3, 1}, {cri[{d, Inf, a, b, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, b, c, a, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, b, d, a, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, b, Inf, a, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, c, b, a, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, c, b, a, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, c, d, a, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, c, Inf, a, b}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, c, Inf, a, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, Inf, a, b, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, Inf, a, d, b}]}]
 + IIi[{3, 1}, {cri[{Inf, b, a, d, c}]}]
 - IIi[{3, 1}, {cri[{Inf, b, a, d, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, c, a, b, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, c, a, d, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, d, b, a, e}]}]
 - IIi[{3, 1}, {cri[{Inf, d, c, a, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, d, e, a, b}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, e, c, a, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, e, c, a, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, e, d, a, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, e, d, a, c}]}] );
 
 wt4DanAllNPrecomputed = (
 + 1/2 IIi[{4}, {cri[{0, b, c, d}]}]
 - 1/2 IIi[{4}, {cri[{0, b, c, e}]}]
 - 2 IIi[{4}, {cri[{0, b, d, Inf}]}]
 + 2 IIi[{4}, {cri[{0, b, e, Inf}]}]
 - 3/2 IIi[{4}, {cri[{0, c, b, d}]}]
 + 1/2 IIi[{4}, {cri[{0, c, b, e}]}]
 - IIi[{4}, {cri[{0, c, e, Inf}]}]
 + IIi[{4}, {cri[{0, c, Inf, b}]}]
 - 1/2 IIi[{4}, {cri[{0, d, b, e}]}]
 + 3/2 IIi[{4}, {cri[{0, d, c, e}]}]
 - IIi[{4}, {cri[{0, d, e, Inf}]}]
 - IIi[{4}, {cri[{0, d, Inf, b}]}]
 - 3 IIi[{4}, {cri[{0, d, Inf, c}]}]
 + 1/2 IIi[{4}, {cri[{0, e, b, d}]}]
 - 1/2 IIi[{4}, {cri[{0, e, c, d}]}]
 + IIi[{4}, {cri[{0, e, Inf, b}]}]
 - 1/2 IIi[{4}, {cri[{0, Inf, b, d}]}]
 + 3/2 IIi[{4}, {cri[{0, Inf, b, e}]}]
 - 3/2 IIi[{4}, {cri[{0, Inf, c, d}]}]
 - 3/2 IIi[{4}, {cri[{0, Inf, c, e}]}]
 - 1/2 IIi[{4}, {cri[{1, b, c, d}]}]
 + 1/2 IIi[{4}, {cri[{1, b, c, e}]}]
 + 2 IIi[{4}, {cri[{1, b, d, Inf}]}]
 - 2 IIi[{4}, {cri[{1, b, e, Inf}]}]
 + 3/2 IIi[{4}, {cri[{1, c, b, d}]}]
 - 1/2 IIi[{4}, {cri[{1, c, b, e}]}]
 + IIi[{4}, {cri[{1, c, e, Inf}]}]
 - IIi[{4}, {cri[{1, c, Inf, b}]}]
 + 1/2 IIi[{4}, {cri[{1, d, b, e}]}]
 - 3/2 IIi[{4}, {cri[{1, d, c, e}]}]
 + IIi[{4}, {cri[{1, d, e, Inf}]}]
 + IIi[{4}, {cri[{1, d, Inf, b}]}]
 + 3 IIi[{4}, {cri[{1, d, Inf, c}]}]
 - 1/2 IIi[{4}, {cri[{1, e, b, d}]}]
 + 1/2 IIi[{4}, {cri[{1, e, c, d}]}]
 - IIi[{4}, {cri[{1, e, Inf, b}]}]
 + 1/2 IIi[{4}, {cri[{1, Inf, b, d}]}]
 - 3/2 IIi[{4}, {cri[{1, Inf, b, e}]}]
 + 3/2 IIi[{4}, {cri[{1, Inf, c, d}]}]
 + 3/2 IIi[{4}, {cri[{1, Inf, c, e}]}]
 + 1/2 IIi[{1, 3}, {cri[{b, d, 0, c, e}]}]
 - 1/2 IIi[{1, 3}, {cri[{b, d, 1, c, e}]}]
 + 1/2 IIi[{1, 3}, {cri[{b, e, 0, d, Inf}]}]
 - 1/2 IIi[{1, 3}, {cri[{b, e, 1, d, Inf}]}]
 - 1/2 IIi[{1, 3}, {cri[{c, d, 0, b, Inf}]}]
 + 1/2 IIi[{1, 3}, {cri[{c, d, 1, b, Inf}]}]
 + 1/2 IIi[{1, 3}, {cri[{c, e, 0, b, d}]}]
 - IIi[{1, 3}, {cri[{c, e, 0, d, Inf}]}]
 - 1/2 IIi[{1, 3}, {cri[{c, e, 1, b, d}]}]
 + IIi[{1, 3}, {cri[{c, e, 1, d, Inf}]}]
 + IIi[{1, 3}, {cri[{d, Inf, 0, b, c}]}]
 - IIi[{1, 3}, {cri[{d, Inf, 1, b, c}]}]
 - 1/2 IIi[{1, 3}, {cri[{e, Inf, 0, b, c}]}]
 - 1/2 IIi[{1, 3}, {cri[{e, Inf, 0, b, d}]}]
 + 1/2 IIi[{1, 3}, {cri[{e, Inf, 1, b, c}]}]
 + 1/2 IIi[{1, 3}, {cri[{e, Inf, 1, b, d}]}]
 - 1/2 IIi[{1, 3}, {cri[{Inf, b, 0, c, e}]}]
 + IIi[{1, 3}, {cri[{Inf, b, 0, d, c}]}]
 - 1/2 IIi[{1, 3}, {cri[{Inf, b, 0, e, c}]}]
 + 1/2 IIi[{1, 3}, {cri[{Inf, b, 1, c, e}]}]
 - IIi[{1, 3}, {cri[{Inf, b, 1, d, c}]}]
 + 1/2 IIi[{1, 3}, {cri[{Inf, b, 1, e, c}]}]
 - 1/2 IIi[{1, 3}, {cri[{Inf, c, 0, b, d}]}]
 + 1/2 IIi[{1, 3}, {cri[{Inf, c, 0, d, e}]}]
 + 1/2 IIi[{1, 3}, {cri[{Inf, c, 1, b, d}]}]
 - 1/2 IIi[{1, 3}, {cri[{Inf, c, 1, d, e}]}]
 + 1/2 IIi[{2, 2}, {cri[{b, d, 0, c, e}]}]
 + 1/2 IIi[{2, 2}, {cri[{b, d, 0, Inf, c}]}]
 - 1/2 IIi[{2, 2}, {cri[{b, d, 1, c, e}]}]
 - 1/2 IIi[{2, 2}, {cri[{b, d, 1, Inf, c}]}]
 - 1/2 IIi[{2, 2}, {cri[{b, e, 0, Inf, c}]}]
 + 1/2 IIi[{2, 2}, {cri[{b, e, 1, Inf, c}]}]
 + 1/2 IIi[{2, 2}, {cri[{c, d, 0, Inf, e}]}]
 - 1/2 IIi[{2, 2}, {cri[{c, d, 1, Inf, e}]}]
 + 1/2 IIi[{2, 2}, {cri[{c, e, 0, b, Inf}]}]
 - 1/2 IIi[{2, 2}, {cri[{c, e, 0, d, Inf}]}]
 - 1/2 IIi[{2, 2}, {cri[{c, e, 1, b, Inf}]}]
 + 1/2 IIi[{2, 2}, {cri[{c, e, 1, d, Inf}]}]
 + IIi[{2, 2}, {cri[{d, Inf, 0, b, c}]}]
 + 1/2 IIi[{2, 2}, {cri[{d, Inf, 0, b, e}]}]
 - IIi[{2, 2}, {cri[{d, Inf, 1, b, c}]}]
 - 1/2 IIi[{2, 2}, {cri[{d, Inf, 1, b, e}]}]
 - 1/2 IIi[{2, 2}, {cri[{e, Inf, 0, b, c}]}]
 - 1/2 IIi[{2, 2}, {cri[{e, Inf, 0, d, b}]}]
 + 1/2 IIi[{2, 2}, {cri[{e, Inf, 0, d, c}]}]
 + 1/2 IIi[{2, 2}, {cri[{e, Inf, 1, b, c}]}]
 + 1/2 IIi[{2, 2}, {cri[{e, Inf, 1, d, b}]}]
 - 1/2 IIi[{2, 2}, {cri[{e, Inf, 1, d, c}]}]
 - 1/2 IIi[{2, 2}, {cri[{Inf, b, 0, c, e}]}]
 + 1/2 IIi[{2, 2}, {cri[{Inf, b, 0, d, c}]}]
 - 1/2 IIi[{2, 2}, {cri[{Inf, b, 0, e, c}]}]
 + 1/2 IIi[{2, 2}, {cri[{Inf, b, 1, c, e}]}]
 - 1/2 IIi[{2, 2}, {cri[{Inf, b, 1, d, c}]}]
 + 1/2 IIi[{2, 2}, {cri[{Inf, b, 1, e, c}]}]
 + 1/2 IIi[{2, 2}, {cri[{Inf, c, 0, b, d}]}]
 + IIi[{2, 2}, {cri[{Inf, c, 0, d, e}]}]
 - 1/2 IIi[{2, 2}, {cri[{Inf, c, 1, b, d}]}]
 - IIi[{2, 2}, {cri[{Inf, c, 1, d, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, d, 0, c, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, d, 0, Inf, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, d, 1, c, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, d, 1, Inf, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, e, 0, d, c}]}]
 - IIi[{3, 1}, {cri[{b, e, 0, Inf, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, e, 1, d, c}]}]
 + IIi[{3, 1}, {cri[{b, e, 1, Inf, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, d, 0, b, e}]}]
 + IIi[{3, 1}, {cri[{c, d, 0, Inf, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, d, 1, b, e}]}]
 - IIi[{3, 1}, {cri[{c, d, 1, Inf, e}]}]
 + 3/2 IIi[{3, 1}, {cri[{d, Inf, 0, b, e}]}]
 - 3/2 IIi[{3, 1}, {cri[{d, Inf, 1, b, e}]}]
 - IIi[{3, 1}, {cri[{e, Inf, 0, b, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, Inf, 0, d, c}]}]
 + IIi[{3, 1}, {cri[{e, Inf, 1, b, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, Inf, 1, d, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, b, 0, c, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, b, 0, d, c}]}]
 + IIi[{3, 1}, {cri[{Inf, b, 0, d, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, b, 0, e, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, b, 1, c, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, b, 1, d, c}]}]
 - IIi[{3, 1}, {cri[{Inf, b, 1, d, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, b, 1, e, c}]}]
 + 3/2 IIi[{3, 1}, {cri[{Inf, c, 0, d, e}]}]
 - 3/2 IIi[{3, 1}, {cri[{Inf, c, 1, d, e}]}]
 + IIi[{1, 1, 1, 1}, {cri[{Inf, 0, 1, b, c, d, e}]}] );
 
wt4DanAllNas31and4Precomputed = (
 - 1/2 IIi[{4}, {cri[{0, b, c, e}]}]
 - 5/2 IIi[{4}, {cri[{0, b, d, Inf}]}]
 + 2 IIi[{4}, {cri[{0, b, e, Inf}]}]
 - IIi[{4}, {cri[{0, b, Inf, c}]}]
 - 2 IIi[{4}, {cri[{0, c, b, d}]}]
 + IIi[{4}, {cri[{0, c, b, e}]}]
 - IIi[{4}, {cri[{0, c, d, Inf}]}]
 - IIi[{4}, {cri[{0, c, e, Inf}]}]
 + IIi[{4}, {cri[{0, c, Inf, b}]}]
 + IIi[{4}, {cri[{0, d, c, e}]}]
 - IIi[{4}, {cri[{0, d, e, Inf}]}]
 - 1/2 IIi[{4}, {cri[{0, d, Inf, b}]}]
 - 4 IIi[{4}, {cri[{0, d, Inf, c}]}]
 - IIi[{4}, {cri[{0, e, c, d}]}]
 - 1/2 IIi[{4}, {cri[{0, e, d, Inf}]}]
 + 3/2 IIi[{4}, {cri[{0, e, Inf, b}]}]
 - IIi[{4}, {cri[{0, e, Inf, c}]}]
 - IIi[{4}, {cri[{0, Inf, b, d}]}]
 + 2 IIi[{4}, {cri[{0, Inf, b, e}]}]
 - 2 IIi[{4}, {cri[{0, Inf, c, d}]}]
 - 3/2 IIi[{4}, {cri[{0, Inf, c, e}]}]
 + 1/2 IIi[{4}, {cri[{1, b, c, e}]}]
 + 5/2 IIi[{4}, {cri[{1, b, d, Inf}]}]
 - 2 IIi[{4}, {cri[{1, b, e, Inf}]}]
 + IIi[{4}, {cri[{1, b, Inf, c}]}]
 + 2 IIi[{4}, {cri[{1, c, b, d}]}]
 - IIi[{4}, {cri[{1, c, b, e}]}]
 + IIi[{4}, {cri[{1, c, d, Inf}]}]
 + IIi[{4}, {cri[{1, c, e, Inf}]}]
 - IIi[{4}, {cri[{1, c, Inf, b}]}]
 - IIi[{4}, {cri[{1, d, c, e}]}]
 + IIi[{4}, {cri[{1, d, e, Inf}]}]
 + 1/2 IIi[{4}, {cri[{1, d, Inf, b}]}]
 + 4 IIi[{4}, {cri[{1, d, Inf, c}]}]
 + IIi[{4}, {cri[{1, e, c, d}]}]
 + 1/2 IIi[{4}, {cri[{1, e, d, Inf}]}]
 - 3/2 IIi[{4}, {cri[{1, e, Inf, b}]}]
 + IIi[{4}, {cri[{1, e, Inf, c}]}]
 + IIi[{4}, {cri[{1, Inf, b, d}]}]
 - 2 IIi[{4}, {cri[{1, Inf, b, e}]}]
 + 2 IIi[{4}, {cri[{1, Inf, c, d}]}]
 + 3/2 IIi[{4}, {cri[{1, Inf, c, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, d, 0, Inf, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, d, 0, Inf, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, d, 1, Inf, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, d, 1, Inf, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, e, 0, d, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, e, 0, Inf, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, e, 1, d, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, e, 1, Inf, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, Inf, c, 0, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, Inf, c, 0, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, Inf, c, 1, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, Inf, c, 1, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, Inf, d, 0, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, Inf, d, 1, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{b, Inf, e, 0, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{b, Inf, e, 1, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, d, 0, b, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, d, 0, Inf, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, d, 1, b, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, d, 1, Inf, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, e, 0, b, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, e, 0, d, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, e, 1, b, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, e, 1, d, Inf}]}]
 + IIi[{3, 1}, {cri[{c, Inf, b, 0, d}]}]
 - IIi[{3, 1}, {cri[{c, Inf, b, 1, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, Inf, d, 0, b}]}]
 + 1/2 IIi[{3, 1}, {cri[{c, Inf, d, 0, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, Inf, d, 1, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{c, Inf, d, 1, e}]}]
 + IIi[{3, 1}, {cri[{c, Inf, e, 0, d}]}]
 - IIi[{3, 1}, {cri[{c, Inf, e, 1, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{d, b, c, 0, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, b, c, 1, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{d, b, e, 0, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, b, e, 1, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{d, b, Inf, 0, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, b, Inf, 1, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{d, c, b, 0, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, c, b, 1, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{d, c, e, 0, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, c, e, 1, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{d, c, Inf, 0, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{d, c, Inf, 1, e}]}]
 - IIi[{3, 1}, {cri[{d, Inf, 0, b, c}]}]
 + IIi[{3, 1}, {cri[{d, Inf, 0, b, e}]}]
 + IIi[{3, 1}, {cri[{d, Inf, 1, b, c}]}]
 - IIi[{3, 1}, {cri[{d, Inf, 1, b, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, b, c, 0, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, b, c, 1, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, b, d, 0, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, b, d, 1, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, b, Inf, 0, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, b, Inf, 1, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, c, b, 0, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, c, b, 0, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, c, b, 1, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, c, b, 1, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, c, d, 0, Inf}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, c, d, 1, Inf}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, c, Inf, 0, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, c, Inf, 0, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, c, Inf, 1, b}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, c, Inf, 1, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, Inf, 0, b, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, Inf, 0, d, b}]}]
 + 1/2 IIi[{3, 1}, {cri[{e, Inf, 1, b, c}]}]
 - 1/2 IIi[{3, 1}, {cri[{e, Inf, 1, d, b}]}]
 - IIi[{3, 1}, {cri[{Inf, b, 0, d, c}]}]
 + IIi[{3, 1}, {cri[{Inf, b, 0, d, e}]}]
 + IIi[{3, 1}, {cri[{Inf, b, 1, d, c}]}]
 - IIi[{3, 1}, {cri[{Inf, b, 1, d, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, c, 0, b, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, c, 0, d, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, c, 1, b, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, c, 1, d, e}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, d, b, 0, e}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, d, b, 1, e}]}]
 + IIi[{3, 1}, {cri[{Inf, d, c, 0, b}]}]
 - IIi[{3, 1}, {cri[{Inf, d, c, 1, b}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, d, e, 0, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, d, e, 1, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, e, c, 0, b}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, e, c, 0, d}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, e, c, 1, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, e, c, 1, d}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, e, d, 0, b}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, e, d, 0, c}]}]
 + 1/2 IIi[{3, 1}, {cri[{Inf, e, d, 1, b}]}]
 - 1/2 IIi[{3, 1}, {cri[{Inf, e, d, 1, c}]}]
 + IIi[{1, 1, 1, 1}, {cri[{Inf, 0, 1, b, c, d, e}]}] );
 
wt4DanAllNas22and4Precomputed = (
- 1/2 IIi[{4}, {cri[{0, b, c, e}]}] 
 - 5/2 IIi[{4}, {cri[{0, b, d, Inf}]}] 
 + 2 IIi[{4}, {cri[{0, b, e, Inf}]}] 
 - IIi[{4}, {cri[{0, b, Inf, c}]}] 
 - 2 IIi[{4}, {cri[{0, c, b, d}]}] 
 + IIi[{4}, {cri[{0, c, b, e}]}] 
 - IIi[{4}, {cri[{0, c, d, Inf}]}] 
 - IIi[{4}, {cri[{0, c, e, Inf}]}] 
 + IIi[{4}, {cri[{0, c, Inf, b}]}] 
 + IIi[{4}, {cri[{0, d, c, e}]}] 
 - IIi[{4}, {cri[{0, d, e, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{0, d, Inf, b}]}] 
 - 4 IIi[{4}, {cri[{0, d, Inf, c}]}] 
 - IIi[{4}, {cri[{0, e, c, d}]}] 
 - 1/2 IIi[{4}, {cri[{0, e, d, Inf}]}] 
 + 3/2 IIi[{4}, {cri[{0, e, Inf, b}]}] 
 - IIi[{4}, {cri[{0, e, Inf, c}]}] 
 - IIi[{4}, {cri[{0, Inf, b, d}]}] 
 + 2 IIi[{4}, {cri[{0, Inf, b, e}]}] 
 - 2 IIi[{4}, {cri[{0, Inf, c, d}]}] 
 - 3/2 IIi[{4}, {cri[{0, Inf, c, e}]}] 
 + 1/2 IIi[{4}, {cri[{1, b, c, e}]}] 
 + 5/2 IIi[{4}, {cri[{1, b, d, Inf}]}] 
 - 2 IIi[{4}, {cri[{1, b, e, Inf}]}] 
 + IIi[{4}, {cri[{1, b, Inf, c}]}] 
 + 2 IIi[{4}, {cri[{1, c, b, d}]}] 
 - IIi[{4}, {cri[{1, c, b, e}]}] 
 + IIi[{4}, {cri[{1, c, d, Inf}]}] 
 + IIi[{4}, {cri[{1, c, e, Inf}]}] 
 - IIi[{4}, {cri[{1, c, Inf, b}]}] 
 - IIi[{4}, {cri[{1, d, c, e}]}] 
 + IIi[{4}, {cri[{1, d, e, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{1, d, Inf, b}]}] 
 + 4 IIi[{4}, {cri[{1, d, Inf, c}]}] 
 + IIi[{4}, {cri[{1, e, c, d}]}] 
 + 1/2 IIi[{4}, {cri[{1, e, d, Inf}]}] 
 - 3/2 IIi[{4}, {cri[{1, e, Inf, b}]}] 
 + IIi[{4}, {cri[{1, e, Inf, c}]}] 
 + IIi[{4}, {cri[{1, Inf, b, d}]}] 
 - 2 IIi[{4}, {cri[{1, Inf, b, e}]}] 
 + 2 IIi[{4}, {cri[{1, Inf, c, d}]}] 
 + 3/2 IIi[{4}, {cri[{1, Inf, c, e}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, d, 0, c, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, d, 0, e, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, d, 0, Inf, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, d, 0, Inf, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, d, 1, c, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, d, 1, e, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, d, 1, Inf, c}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, d, 1, Inf, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, e, 0, c, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, e, 0, c, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, e, 0, d, c}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, e, 0, Inf, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, e, 1, c, d}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, e, 1, c, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, e, 1, d, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, e, 1, Inf, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, Inf, c, 0, d}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, Inf, c, 0, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, Inf, c, 1, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, Inf, c, 1, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, Inf, c, d, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, Inf, c, d, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, Inf, c, e, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, Inf, c, e, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, Inf, d, 0, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, Inf, d, 1, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, Inf, d, c, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, Inf, d, c, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, Inf, e, 0, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, Inf, e, 1, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{b, Inf, e, c, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{b, Inf, e, c, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, d, 0, b, e}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, d, 0, e, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, d, 0, e, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, d, 0, Inf, e}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, d, 1, b, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, d, 1, e, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, d, 1, e, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, d, 1, Inf, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, e, 0, b, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, e, 0, d, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, e, 0, Inf, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, e, 0, Inf, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, e, 1, b, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, e, 1, d, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, e, 1, Inf, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, e, 1, Inf, d}]}] 
 - 1/2 IIi[{2, 2}, {cri[{c, Inf, b, 0, d}]}] 
 + 1/2 IIi[{2, 2}, {cri[{c, Inf, b, 1, d}]}] 
 + 1/2 IIi[{2, 2}, {cri[{c, Inf, b, d, 0}]}] 
 - 1/2 IIi[{2, 2}, {cri[{c, Inf, b, d, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, Inf, d, 0, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, Inf, d, 0, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, Inf, d, 1, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, Inf, d, 1, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, Inf, d, b, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, Inf, d, b, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{c, Inf, d, e, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{c, Inf, d, e, 1}]}] 
 - 1/2 IIi[{2, 2}, {cri[{c, Inf, e, 0, d}]}] 
 + 1/2 IIi[{2, 2}, {cri[{c, Inf, e, 1, d}]}] 
 + 1/2 IIi[{2, 2}, {cri[{c, Inf, e, d, 0}]}] 
 - 1/2 IIi[{2, 2}, {cri[{c, Inf, e, d, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, b, c, 0, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, b, c, 1, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, b, c, Inf, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, b, c, Inf, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, b, e, 0, c}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, b, e, 1, c}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, b, e, c, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, b, e, c, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, b, Inf, 0, c}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, b, Inf, 1, c}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, b, Inf, c, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, b, Inf, c, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, c, b, 0, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, c, b, 1, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, c, b, Inf, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, c, b, Inf, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, c, e, 0, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, c, e, 1, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, c, e, Inf, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, c, e, Inf, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, c, Inf, 0, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, c, Inf, 1, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{d, c, Inf, e, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{d, c, Inf, e, 1}]}] 
 + 1/2 IIi[{2, 2}, {cri[{d, Inf, 0, b, c}]}] 
 - 1/2 IIi[{2, 2}, {cri[{d, Inf, 0, b, e}]}] 
 - 1/2 IIi[{2, 2}, {cri[{d, Inf, 0, c, b}]}] 
 + 1/2 IIi[{2, 2}, {cri[{d, Inf, 0, e, b}]}] 
 - 1/2 IIi[{2, 2}, {cri[{d, Inf, 1, b, c}]}] 
 + 1/2 IIi[{2, 2}, {cri[{d, Inf, 1, b, e}]}] 
 + 1/2 IIi[{2, 2}, {cri[{d, Inf, 1, c, b}]}] 
 - 1/2 IIi[{2, 2}, {cri[{d, Inf, 1, e, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, b, c, 0, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, b, c, 1, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, b, c, Inf, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, b, c, Inf, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, b, d, 0, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, b, d, 1, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, b, d, Inf, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, b, d, Inf, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, b, Inf, 0, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, b, Inf, 1, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, b, Inf, c, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, b, Inf, c, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, b, 0, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, b, 0, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, b, 1, d}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, b, 1, Inf}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, b, d, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, b, d, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, b, Inf, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, b, Inf, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, d, 0, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, d, 1, Inf}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, d, Inf, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, d, Inf, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, Inf, 0, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, Inf, 0, d}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, Inf, 1, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, Inf, 1, d}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, Inf, b, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, Inf, b, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, c, Inf, d, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, c, Inf, d, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, Inf, 0, b, c}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, Inf, 0, b, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, Inf, 0, c, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, Inf, 0, d, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, Inf, 1, b, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{e, Inf, 1, b, d}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, Inf, 1, c, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{e, Inf, 1, d, b}]}] 
 - 1/2 IIi[{2, 2}, {cri[{Inf, b, 0, c, d}]}] 
 + 1/2 IIi[{2, 2}, {cri[{Inf, b, 0, d, c}]}] 
 - 1/2 IIi[{2, 2}, {cri[{Inf, b, 0, d, e}]}] 
 + 1/2 IIi[{2, 2}, {cri[{Inf, b, 0, e, d}]}] 
 + 1/2 IIi[{2, 2}, {cri[{Inf, b, 1, c, d}]}] 
 - 1/2 IIi[{2, 2}, {cri[{Inf, b, 1, d, c}]}] 
 + 1/2 IIi[{2, 2}, {cri[{Inf, b, 1, d, e}]}] 
 - 1/2 IIi[{2, 2}, {cri[{Inf, b, 1, e, d}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, c, 0, b, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, c, 0, d, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, c, 0, d, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, c, 0, e, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, c, 1, b, d}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, c, 1, d, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, c, 1, d, e}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, c, 1, e, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, d, b, 0, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, d, b, 1, e}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, d, b, e, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, d, b, e, 1}]}] 
 - 1/2 IIi[{2, 2}, {cri[{Inf, d, c, 0, b}]}] 
 + 1/2 IIi[{2, 2}, {cri[{Inf, d, c, 1, b}]}] 
 + 1/2 IIi[{2, 2}, {cri[{Inf, d, c, b, 0}]}] 
 - 1/2 IIi[{2, 2}, {cri[{Inf, d, c, b, 1}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, d, e, 0, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, d, e, 1, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, d, e, b, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, d, e, b, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, e, c, 0, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, e, c, 0, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, e, c, 1, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, e, c, 1, d}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, e, c, b, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, e, c, b, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, e, c, d, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, e, c, d, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, e, d, 0, b}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, e, d, 0, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, e, d, 1, b}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, e, d, 1, c}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, e, d, b, 0}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, e, d, b, 1}]}] 
 + 1/4 IIi[{2, 2}, {cri[{Inf, e, d, c, 0}]}] 
 - 1/4 IIi[{2, 2}, {cri[{Inf, e, d, c, 1}]}] 
 + IIi[{1, 1, 1, 1}, {cri[{Inf, 0, 1, b, c, d, e}]}] );
 
wt4danStructuredLowerPrecomputed = (
- 1/2 IIi[{4}, {cri[{a, c, e, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{a, d, b, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{a, d, e, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{a, e, c, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{b, a, d, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{b, d, a, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{b, e, a, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{b, e, c, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{c, a, b, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{c, a, d, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{c, b, e, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{c, e, b, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{d, a, c, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{d, b, c, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{d, b, e, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{d, c, a, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{e, b, d, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{e, c, a, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{e, c, d, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{e, d, b, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, b, c, d, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, b, c, d, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, b, c, Inf, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, b, d, c, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, b, d, c, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, b, d, Inf, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, b, Inf, c, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, b, Inf, d, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, e, c, d, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, e, c, d, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, e, c, Inf, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, e, d, c, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, e, d, c, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, e, d, Inf, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, e, Inf, c, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, e, Inf, d, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, Inf, c, d, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, Inf, c, d, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, Inf, d, c, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, Inf, d, c, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, a, d, e, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, a, d, e, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, a, d, Inf, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, a, e, d, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, a, e, d, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, a, e, Inf, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, a, Inf, d, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, a, Inf, e, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, c, d, e, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, c, d, e, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, c, d, Inf, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, c, e, d, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, c, e, d, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, c, e, Inf, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, c, Inf, d, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, c, Inf, e, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, Inf, d, e, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, Inf, d, e, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, Inf, e, d, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, Inf, e, d, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, b, a, e, d}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, b, a, e, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, b, a, Inf, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, b, e, a, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, b, e, a, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, b, e, Inf, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, b, Inf, a, d}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, b, Inf, e, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, d, a, e, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, d, a, e, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, d, a, Inf, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, d, e, a, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, d, e, a, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, d, e, Inf, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, d, Inf, a, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, d, Inf, e, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, Inf, a, e, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, Inf, a, e, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, Inf, e, a, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, Inf, e, a, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, c, a, b, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, c, a, b, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, c, a, Inf, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, c, b, a, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, c, b, a, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, c, b, Inf, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, c, Inf, a, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, c, Inf, b, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, e, a, b, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, e, a, b, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, e, a, Inf, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, e, b, a, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, e, b, a, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, e, b, Inf, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, e, Inf, a, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, e, Inf, b, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, Inf, a, b, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, Inf, a, b, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, Inf, b, a, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, Inf, b, a, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, a, b, c, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, a, b, c, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, a, b, Inf, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, a, c, b, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, a, c, b, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, a, c, Inf, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, a, Inf, b, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, a, Inf, c, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, d, b, c, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, d, b, c, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, d, b, Inf, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, d, c, b, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, d, c, b, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, d, c, Inf, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, d, Inf, b, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, d, Inf, c, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, Inf, b, c, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, Inf, b, c, d}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, Inf, c, b, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, Inf, c, b, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, a, b, c, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, a, c, b, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, a, d, e, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, a, e, d, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, b, a, e, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, b, c, d, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, b, d, c, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, b, e, a, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, c, a, b, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, c, b, a, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, c, d, e, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, c, e, d, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, d, a, e, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, d, b, c, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, d, c, b, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, d, e, a, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, e, a, b, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, e, b, a, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, e, c, d, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, e, d, c, b}]}] );
 
wt4DanStructuredPrecomputed = (
 + 1/2 IIi[{4}, {cri[{a, c, e, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{a, d, b, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{a, d, e, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{a, e, c, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{b, a, d, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{b, d, a, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{b, d, f, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{b, e, a, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{b, e, f, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{b, f, d, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{c, a, b, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{c, a, d, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{c, f, b, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{c, f, d, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{d, a, c, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{d, c, a, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{d, c, f, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{d, f, c, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{e, c, a, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{e, c, f, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{f, c, e, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{f, d, b, Inf}]}] 
 + 1/2 IIi[{4}, {cri[{f, d, e, Inf}]}] 
 - 1/2 IIi[{4}, {cri[{f, e, c, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, b, c, d, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, b, c, d, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, b, c, Inf, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, b, d, c, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, b, d, c, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, b, d, Inf, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, b, Inf, c, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, b, Inf, d, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, e, c, d, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, e, c, d, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, e, c, Inf, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, e, d, c, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, e, d, c, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, e, d, Inf, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, e, Inf, c, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, e, Inf, d, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{a, Inf, c, d, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{a, Inf, c, d, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{a, Inf, d, c, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{a, Inf, d, c, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, a, d, e, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, a, d, e, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, a, d, Inf, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, a, e, d, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, a, e, d, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, a, e, Inf, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, a, Inf, d, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, a, Inf, e, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, c, d, e, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, c, d, e, f}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, c, d, Inf, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, c, d, Inf, f}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, c, e, d, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, c, e, d, f}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, c, e, Inf, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, c, e, Inf, f}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, c, Inf, d, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, c, Inf, d, f}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, c, Inf, e, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, c, Inf, e, f}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, f, d, e, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, f, d, e, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, f, d, Inf, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, f, e, d, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, f, e, d, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, f, e, Inf, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, f, Inf, d, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, f, Inf, e, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{b, Inf, d, e, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{b, Inf, d, e, f}]}] 
 - 3/20 IIi[{3, 1}, {cri[{b, Inf, e, d, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{b, Inf, e, d, f}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, b, a, e, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, b, a, e, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, b, a, Inf, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, b, e, a, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, b, e, a, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, b, e, f, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, b, e, f, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, b, f, e, d}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, b, f, e, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, b, f, Inf, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, b, Inf, a, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, b, Inf, f, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, d, a, e, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, d, a, e, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, d, a, Inf, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, d, e, a, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, d, e, a, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, d, e, f, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, d, e, f, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, d, f, e, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, d, f, e, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, d, f, Inf, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, d, Inf, a, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, d, Inf, f, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, Inf, a, e, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, Inf, a, e, d}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, Inf, e, a, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, Inf, e, a, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{c, Inf, e, f, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{c, Inf, e, f, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{c, Inf, f, e, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{c, Inf, f, e, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, c, a, b, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, c, a, b, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, c, a, Inf, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, c, b, a, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, c, b, a, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, c, b, f, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, c, b, f, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, c, f, b, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, c, f, b, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, c, f, Inf, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, c, Inf, a, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, c, Inf, f, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, e, a, b, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, e, a, b, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, e, a, Inf, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, e, b, a, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, e, b, a, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, e, b, f, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, e, b, f, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, e, f, b, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, e, f, b, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, e, f, Inf, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, e, Inf, a, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, e, Inf, f, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, Inf, a, b, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, Inf, a, b, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, Inf, b, a, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, Inf, b, a, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{d, Inf, b, f, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{d, Inf, b, f, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{d, Inf, f, b, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{d, Inf, f, b, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, a, b, c, d}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, a, b, c, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, a, b, Inf, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, a, c, b, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, a, c, b, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, a, c, Inf, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, a, Inf, b, d}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, a, Inf, c, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, d, b, c, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, d, b, c, f}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, d, b, Inf, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, d, b, Inf, f}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, d, c, b, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, d, c, b, f}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, d, c, Inf, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, d, c, Inf, f}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, d, Inf, b, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, d, Inf, b, f}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, d, Inf, c, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, d, Inf, c, f}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, f, b, c, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, f, b, c, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, f, b, Inf, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, f, c, b, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, f, c, b, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, f, c, Inf, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, f, Inf, b, d}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, f, Inf, c, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{e, Inf, b, c, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{e, Inf, b, c, f}]}] 
 - 1/20 IIi[{3, 1}, {cri[{e, Inf, c, b, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{e, Inf, c, b, f}]}] 
 + 1/20 IIi[{3, 1}, {cri[{f, b, c, d, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{f, b, c, d, Inf}]}] 
 - 1/20 IIi[{3, 1}, {cri[{f, b, c, Inf, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{f, b, d, c, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{f, b, d, c, Inf}]}] 
 + 3/20 IIi[{3, 1}, {cri[{f, b, d, Inf, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{f, b, Inf, c, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{f, b, Inf, d, e}]}] 
 + 3/20 IIi[{3, 1}, {cri[{f, e, c, d, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{f, e, c, d, Inf}]}] 
 - 3/20 IIi[{3, 1}, {cri[{f, e, c, Inf, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{f, e, d, c, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{f, e, d, c, Inf}]}] 
 + 1/20 IIi[{3, 1}, {cri[{f, e, d, Inf, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{f, e, Inf, c, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{f, e, Inf, d, b}]}] 
 - 3/20 IIi[{3, 1}, {cri[{f, Inf, c, d, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{f, Inf, c, d, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{f, Inf, d, c, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{f, Inf, d, c, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, a, b, c, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, a, c, b, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, a, d, e, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, a, e, d, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, b, a, e, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, b, e, a, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, b, e, f, d}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, b, f, e, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, c, a, b, e}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, c, b, a, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, c, b, f, e}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, c, d, e, a}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, c, d, e, f}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, c, e, d, a}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, c, e, d, f}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, c, f, b, e}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, d, a, e, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, d, b, c, a}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, d, b, c, f}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, d, c, b, a}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, d, c, b, f}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, d, e, a, b}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, d, e, f, b}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, d, f, e, b}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, e, a, b, c}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, e, b, a, c}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, e, b, f, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, e, f, b, c}]}] 
 - 1/20 IIi[{3, 1}, {cri[{Inf, f, b, c, d}]}] 
 + 3/20 IIi[{3, 1}, {cri[{Inf, f, c, b, d}]}] 
 - 3/20 IIi[{3, 1}, {cri[{Inf, f, d, e, c}]}] 
 + 1/20 IIi[{3, 1}, {cri[{Inf, f, e, d, c}]}] 
 + IIi[{1, 1, 1, 1}, {cri[{Inf, a, f, b, c, d, e}]}] );